blog/urls.py
from django.urls import path
from . import views

app_name='blog'
urlpatterns=[
    path('',views.frontpage, name='blogs'),
    path('<slug:slug>/',views.post_detail, name="posts")
]

study_dais/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
# from blog.views import frontpage
import app_users

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('blog/',include('blog.urls')),
    path('',include('pwa.urls'))
    # path('quizes/', include('quizes.urls',namespace='quiz')),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title= models.CharField(max_length=225)
    slug=models.SlugField()
    intro=models.TextField()
    body=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=['-date_added']

blog/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def frontpage(request):
    posts=Post.objects.all()

    return render(request, 'blog/base.html',{'posts':posts})

def post_detail(request,slug):
    post=Post.objects.get(slug=slug)
    return render(request, 'blog/post_detail.html',{'post':post})

blog/templates/blog/base.html
{% extends 'home.html' %}
{% load static %}
{% block title %} Announcements {% endblock %}
{% block content %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Announcements </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'blog:blogs' %}">Announcements</a></li>
            
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Inspiration does exist, but it must find you working.<br/></h4><div style="text-align:right">Pablo Picasso</div>
  </div>
</header>


<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;"><u>Everyday Announcements</u></h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text" style="font-family:cursive;font-size:20px">The announcements regarding the classes and their respective teachers will be uploaded here by the Admin.</p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row">
      {% for post in posts %}<div class="col-md-4 d-flex mb-5 justify-content-center">
                          <div class="card card-std text-center" style="width: 20rem;">
                            <div class="card-body text-center">
                              <h4 class="card-title" style="color:#ff5722;">{{post.title}}</h4>
        <small>Posted at {{post.date_added}} </small>
        <p class="card-text">{{post.intro|truncatechars:75}}</p>
        {% if user.is_authenticated %}
        <a href="{% url 'blog:posts' post.slug %}" class="btn btn-primary" style="background-color:#00bcd4;">Read more</a>
        {%else%}
        <p>Register or login to start learning</p>
        <a href="{% url 'user_login' %}" class="btn btn-std" style="background-color:#00bcd4;">Login</a>
        <a href="{% url 'register' %}" class="btn btn-primary" style="background-color:#00bcd4;">Register</a>
        {%endif%}
      </div>
    </div>
  </div>
  {% endfor %}
  </div>
  </section>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %} Post Details {% endblock %}

{% block content %}
        <h1 class="title">{{post.title}}<h1>

          <small>Posted at {{post.date_added}} </small>
          <p><strong>{{post.intro}}</strong></p>
          <p>{{post.body}}</p>
{% endblock %}